### ISSUE TITLE
add your hackerrank solutions

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Deeksha-Rawat/Hackerrank#1]

**Comment by singhsuryanshu** [comment]
I am adding my python solutions.

**Comment by Deeksha-Rawat** [comment]
thanks @singhsuryanshu for the contribution.

**Comment by Srijan7777** [comment]
Can I contribute to this?
I'll add solutions in C++

**Comment by Deeksha-Rawat** [comment]
Ya sure @Srijan7777 sure go for it...
But you need to make a c++ folder and then add your solutions 😇

**Comment by him9666** [comment]
@Deeksha-Rawat  can i add SQL solutions in new folder? I completed 48 out of 58 practice tests of hacker rank

**Comment by Deeksha-Rawat** [comment]
@him9666 sure you can😊
